const id = Number(new Date());

const jobs = {
  jobs: [
    {
      id: id,
      posisi: "Back-end Developer",
      type: "Paruh Waktu",
      salary: "1 JT - 3 JT",
      logo: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y29tcGFueXxlbnwwfHwwfHx8MA%3D%3D",
      company: "PT. Solusi Digital",
    },
    {
      id: id,
      posisi: "Front-end Developer",
      type: "Penuh Waktu",
      salary: "3 JT - 5 JT",
      logo: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y29tcGFueXxlbnwwfHwwfHx8MA%3D%3D",
      company: "PT. Tech Innovate",
    },
    {
      id: id,
      posisi: "UI/UX Designer",
      type: "Freelance",
      salary: "2.5 JT - 4 JT",
      logo: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y29tcGFueXxlbnwwfHwwfHx8MA%3D%3D",
      company: "Creative Design Studio",
    },
    {
      id: id,
      posisi: "Data Scientist",
      type: "Penuh Waktu",
      salary: "5 JT - 8 JT",
      logo: "https://example.com/logos/data-ai.png",
      company: "Data AI Solutions",
    },
    {
      id: id,
      posisi: "Mobile Developer",
      type: "Paruh Waktu",
      salary: "2 JT - 4 JT",
      logo: "https://example.com/logos/app-masters.png",
      company: "App Masters",
    },
    {
      id: id,
      posisi: "DevOps Engineer",
      type: "Penuh Waktu",
      salary: "6 JT - 10 JT",
      logo: "https://example.com/logos/cloud-tech.png",
      company: "Cloud Tech Indonesia",
    },
    {
      id: id,
      posisi: "Product Manager",
      type: "Penuh Waktu",
      salary: "8 JT - 12 JT",
      logo: "https://example.com/logos/product-labs.png",
      company: "Product Labs",
    },
    {
      id: id,
      posisi: "Quality Assurance",
      type: "Kontrak",
      salary: "3 JT - 5 JT",
      logo: "https://example.com/logos/qa-specialists.png",
      company: "QA Specialists",
    },
    {
      id: id,
      posisi: "System Analyst",
      type: "Penuh Waktu",
      salary: "5 JT - 7 JT",
      logo: "https://example.com/logos/system-arch.png",
      company: "System Architecture Co.",
    },
    {
      id: id,
      posisi: "Network Engineer",
      type: "Penuh Waktu",
      salary: "4 JT - 6 JT",
      logo: "https://example.com/logos/net-solutions.png",
      company: "Network Solutions",
    },
    {
      id: id,
      posisi: "Digital Marketing",
      type: "Freelance",
      salary: "2 JT - 4 JT",
      logo: "https://example.com/logos/marketing-plus.png",
      company: "Marketing Plus",
    },
    {
      id: id,
      posisi: "Content Writer",
      type: "Remote",
      salary: "1.5 JT - 3 JT",
      logo: "https://example.com/logos/content-creators.png",
      company: "Content Creators Inc.",
    },
    {
      id: id,
      posisi: "Graphic Designer",
      type: "Paruh Waktu",
      salary: "2 JT - 3.5 JT",
      logo: "https://example.com/logos/visual-arts.png",
      company: "Visual Arts Studio",
    },
    {
      id: id,
      posisi: "Database Administrator",
      type: "Penuh Waktu",
      salary: "4 JT - 6 JT",
      logo: "https://example.com/logos/data-manage.png",
      company: "Data Management Ltd.",
    },
    {
      id: id,
      posisi: "Cybersecurity Specialist",
      type: "Penuh Waktu",
      salary: "7 JT - 12 JT",
      logo: "https://example.com/logos/secure-tech.png",
      company: "Secure Tech Indonesia",
    },
    {
      id: id,
      posisi: "Business Analyst",
      type: "Kontrak",
      salary: "5 JT - 8 JT",
      logo: "https://example.com/logos/business-solutions.png",
      company: "Business Solutions",
    },
    {
      id: id,
      posisi: "Full-stack Developer",
      type: "Remote",
      salary: "4 JT - 7 JT",
      logo: "https://example.com/logos/web-creators.png",
      company: "Web Creators",
    },
    {
      id: id,
      posisi: "IT Support",
      type: "Paruh Waktu",
      salary: "2 JT - 3 JT",
      logo: "https://example.com/logos/it-helpdesk.png",
      company: "IT Helpdesk Services",
    },
    {
      id: id,
      posisi: "Project Manager",
      type: "Penuh Waktu",
      salary: "9 JT - 14 JT",
      logo: "https://example.com/logos/project-leaders.png",
      company: "Project Leaders",
    },
    {
      id: id,
      posisi: "AI Engineer",
      type: "Penuh Waktu",
      salary: "8 JT - 15 JT",
      logo: "https://example.com/logos/ai-future.png",
      company: "AI Future Technologies",
    },
  ],
};

export { jobs };
